Adding git status check

diff --git a/.github/workflows/updateData.yml b/.github/workflows/updateData.yml
--- a/.github/workflows/updateData.yml
+++ b/.github/workflows/updateData.yml
@@ -1,6 +1,6 @@
 # This is a basic workflow to help you get started with Actions
 
-name: py
+name: update_google_data
 # on:
 #   schedule:
 #     - cron: "*/5 * * * *" #runs at 00:00 UTC everyday
@@ -31,7 +31,17 @@ jobs:
         run: |
           git config --global user.name "github-actions[bot]"
           git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
-
+  
           git add dashApp/data/google_mobility_australia.csv
-          git commit -m "Updating google data"
-          git push
+          
+          set +e  # Grep succeeds with nonzero exit codes to show results.
+          git status | grep modified
+          if [ $? -eq 0 ]
+          then
+              set -e
+              git commit -m "Updating google data - $(date)"
+              git push
+          else
+              set -e
+              echo "No changes since last run"
+          fi
